export const allCategory= [
    "Civil Engineering",
    "ComputerScience Engineering",
    "Electrical Engineering",
    "Electronics Engineering",
    "Mechanical Engineering",
    "Gate CSE",
    "Gate EE",
    "Gate ECE",
    "Gate CE",
    "Gate ME",
    "AutoCad",
    "Cloud Computing",
    "Web Development",
    "App Development",
    "Competitive Programming",
    "Cricket",
    "Basketball",
    "Badminton",
    "Volleyball",
    "Table Tennis",
    "Chess",
    "Technical",
    "Cultural",
    "Educational",
    "Sports",
    "Music",
    "Drama",
    "Dance",
    "Art & Craft",
]
export const category_Data ={
    "Academics":[
        "Civil Engineering",
        "ComputerScience Engineering",
        "Electrical Engineering",
        "Electronics Engineering",
        "Mechanical Engineering",
    ],
    "Sports":[
        "Cricket",
        "Basketball",
        "Badminton",
        "Volleyball",
        "Table Tennis",
        "Chess",
    ],
    "Events":[
        "Technical",
        "Cultural",
        "Educational",
        "Sports",
        "Music",
        "Drama",
        "Dance",
        "Art & Craft"
    ],
    "Exams":[
        "Gate CSE",
        "Gate EE",
        "Gate ECE",
        "Gate CE",
        "Gate ME",
    ],
    "Technical":[     
        "AutoCad",
        "Cloud Computing",
        "Web Development",
        "App Development",
        "Competitive Programming",
    ],
    "Non-Technical":[
        "Aptitude",
    ]
}