const categoryData=[
    "Academic",
    "Civil Engineering",
    "ComputerScience Engineering",
    "Electrical Engineering",
    "Electronics Engineering",
    "Mechanical Engineering",
    "Gate CSE",
    "Gate EE",
    "Gate ECE",
    "Gate CE",
    "Gate ME",
    "AutoCad",
    "Cloud Computing",
    "Web Development",
    "App Development",
    "Competitive Programming",
    "Sports",
    "Cricket",
    "Basketball",
    "Badminton",
    "Volleyball",
    "Table Tennis",
    "Chess",
    "Events",
    "Technical",
    "Cultural",
    "Educational",
    "Sports",
    "Music",
    "Drama",
    "Dance",
    "Art & Craft"
]

export default categoryData;
